#!/bin/sh

if [ ! -f .initialized ]; then
	# Container is initialized according the environment variables
	# passed to the container to setup Phabricator.
	/usr/local/bin/setup-phabricator
fi

/srv/phabricator/phabricator/bin/phd start && echo "Phabricator daemons launched"
/run.sh && echo "Nginx/PHP server launched"
